package hedy.level1.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.EditorAspectDescriptorBase;
import org.jetbrains.annotations.NotNull;
import java.util.Collection;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import java.util.Collections;
import jetbrains.mps.openapi.editor.descriptor.SubstituteMenu;
import jetbrains.mps.lang.smodel.ConceptSwitchIndex;
import jetbrains.mps.lang.smodel.ConceptSwitchIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class EditorAspectDescriptorImpl extends EditorAspectDescriptorBase {
  @NotNull
  public Collection<ConceptEditor> getDeclaredEditors(SAbstractConcept concept) {
    SAbstractConcept cncpt = ((SAbstractConcept) concept);
    switch (conceptIndex.index(cncpt)) {
      case 0:
        return Collections.<ConceptEditor>singletonList(new Command_Editor());
      case 1:
        return Collections.<ConceptEditor>singletonList(new EmptyStatement_Editor());
      case 2:
        return Collections.<ConceptEditor>singletonList(new Program_Editor());
      case 3:
        return Collections.<ConceptEditor>singletonList(new Text_Editor());
      default:
    }
    return Collections.<ConceptEditor>emptyList();
  }


  @NotNull
  @Override
  public Collection<SubstituteMenu> getDeclaredDefaultSubstituteMenus(SAbstractConcept concept) {
    SAbstractConcept cncpt = concept;
    switch (conceptIndex1.index(cncpt)) {
      case 0:
        return Collections.<SubstituteMenu>singletonList(new EmptyStatement_SubstituteMenu());
      default:
    }
    return Collections.<SubstituteMenu>emptyList();
  }

  private static final ConceptSwitchIndex conceptIndex = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0xe95a561e9854400eL, 0xbe65901f7b189932L, 0x4f97f3026298f0e9L), MetaIdFactory.conceptId(0xe95a561e9854400eL, 0xbe65901f7b189932L, 0x3ff65ed398155e02L), MetaIdFactory.conceptId(0xe95a561e9854400eL, 0xbe65901f7b189932L, 0x4f97f3026298f0c4L), MetaIdFactory.conceptId(0xe95a561e9854400eL, 0xbe65901f7b189932L, 0x4f97f3026299a369L)).seal();
  private static final ConceptSwitchIndex conceptIndex1 = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0xe95a561e9854400eL, 0xbe65901f7b189932L, 0x3ff65ed398155e02L)).seal();
}
