package hedy.level1.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int AskCommand = 0;
  public static final int Command = 1;
  public static final int EchoCommand = 2;
  public static final int EmptyStatement = 3;
  public static final int PrintCommand = 4;
  public static final int Program = 5;
  public static final int Statement = 6;
  public static final int Text = 7;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0xe95a561e9854400eL, 0xbe65901f7b189932L);
    builder.put(0x4f97f3026298f0efL, AskCommand);
    builder.put(0x4f97f3026298f0e9L, Command);
    builder.put(0x4f97f3026298f0f0L, EchoCommand);
    builder.put(0x3ff65ed398155e02L, EmptyStatement);
    builder.put(0x4f97f3026298f0eeL, PrintCommand);
    builder.put(0x4f97f3026298f0c4L, Program);
    builder.put(0x3ff65ed398155e03L, Statement);
    builder.put(0x4f97f3026299a369L, Text);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
