package hedy.level1.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptAskCommand = createDescriptorForAskCommand();
  /*package*/ final ConceptDescriptor myConceptCommand = createDescriptorForCommand();
  /*package*/ final ConceptDescriptor myConceptEchoCommand = createDescriptorForEchoCommand();
  /*package*/ final ConceptDescriptor myConceptEmptyStatement = createDescriptorForEmptyStatement();
  /*package*/ final ConceptDescriptor myConceptPrintCommand = createDescriptorForPrintCommand();
  /*package*/ final ConceptDescriptor myConceptProgram = createDescriptorForProgram();
  /*package*/ final ConceptDescriptor myConceptStatement = createDescriptorForStatement();
  /*package*/ final ConceptDescriptor myConceptText = createDescriptorForText();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptAskCommand, myConceptCommand, myConceptEchoCommand, myConceptEmptyStatement, myConceptPrintCommand, myConceptProgram, myConceptStatement, myConceptText);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.AskCommand:
        return myConceptAskCommand;
      case LanguageConceptSwitch.Command:
        return myConceptCommand;
      case LanguageConceptSwitch.EchoCommand:
        return myConceptEchoCommand;
      case LanguageConceptSwitch.EmptyStatement:
        return myConceptEmptyStatement;
      case LanguageConceptSwitch.PrintCommand:
        return myConceptPrintCommand;
      case LanguageConceptSwitch.Program:
        return myConceptProgram;
      case LanguageConceptSwitch.Statement:
        return myConceptStatement;
      case LanguageConceptSwitch.Text:
        return myConceptText;
      default:
        return null;
    }
  }


  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForAskCommand() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("hedy.level1", "AskCommand", 0xe95a561e9854400eL, 0xbe65901f7b189932L, 0x4f97f3026298f0efL);
    b.class_(false, false, false);
    b.super_("hedy.level1.structure.Command", 0xe95a561e9854400eL, 0xbe65901f7b189932L, 0x4f97f3026298f0e9L);
    b.origin("r:1564bb04-b8a2-4dfa-b7da-07b6754fa517(hedy.level1.structure)/5735319842049290479");
    b.version(2);
    b.alias("ask");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForCommand() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("hedy.level1", "Command", 0xe95a561e9854400eL, 0xbe65901f7b189932L, 0x4f97f3026298f0e9L);
    b.class_(false, true, false);
    b.super_("hedy.level1.structure.Statement", 0xe95a561e9854400eL, 0xbe65901f7b189932L, 0x3ff65ed398155e03L);
    b.origin("r:1564bb04-b8a2-4dfa-b7da-07b6754fa517(hedy.level1.structure)/5735319842049290473");
    b.version(2);
    b.aggregate("text", 0x4f97f3026299a366L).target(0xe95a561e9854400eL, 0xbe65901f7b189932L, 0x4f97f3026299a369L).optional(false).ordered(true).multiple(false).origin("5735319842049336166").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForEchoCommand() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("hedy.level1", "EchoCommand", 0xe95a561e9854400eL, 0xbe65901f7b189932L, 0x4f97f3026298f0f0L);
    b.class_(false, false, false);
    b.super_("hedy.level1.structure.Command", 0xe95a561e9854400eL, 0xbe65901f7b189932L, 0x4f97f3026298f0e9L);
    b.origin("r:1564bb04-b8a2-4dfa-b7da-07b6754fa517(hedy.level1.structure)/5735319842049290480");
    b.version(2);
    b.alias("echo");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForEmptyStatement() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("hedy.level1", "EmptyStatement", 0xe95a561e9854400eL, 0xbe65901f7b189932L, 0x3ff65ed398155e02L);
    b.class_(false, false, false);
    b.super_("hedy.level1.structure.Statement", 0xe95a561e9854400eL, 0xbe65901f7b189932L, 0x3ff65ed398155e03L);
    b.origin("r:1564bb04-b8a2-4dfa-b7da-07b6754fa517(hedy.level1.structure)/4608975531542928898");
    b.version(2);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForPrintCommand() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("hedy.level1", "PrintCommand", 0xe95a561e9854400eL, 0xbe65901f7b189932L, 0x4f97f3026298f0eeL);
    b.class_(false, false, false);
    b.super_("hedy.level1.structure.Command", 0xe95a561e9854400eL, 0xbe65901f7b189932L, 0x4f97f3026298f0e9L);
    b.origin("r:1564bb04-b8a2-4dfa-b7da-07b6754fa517(hedy.level1.structure)/5735319842049290478");
    b.version(2);
    b.alias("print");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForProgram() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("hedy.level1", "Program", 0xe95a561e9854400eL, 0xbe65901f7b189932L, 0x4f97f3026298f0c4L);
    b.class_(false, false, true);
    b.origin("r:1564bb04-b8a2-4dfa-b7da-07b6754fa517(hedy.level1.structure)/5735319842049290436");
    b.version(2);
    b.aggregate("statements", 0x4f97f3026298f0e6L).target(0xe95a561e9854400eL, 0xbe65901f7b189932L, 0x3ff65ed398155e03L).optional(true).ordered(true).multiple(true).origin("5735319842049290470").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForStatement() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("hedy.level1", "Statement", 0xe95a561e9854400eL, 0xbe65901f7b189932L, 0x3ff65ed398155e03L);
    b.class_(false, true, false);
    b.origin("r:1564bb04-b8a2-4dfa-b7da-07b6754fa517(hedy.level1.structure)/4608975531542928899");
    b.version(2);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForText() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("hedy.level1", "Text", 0xe95a561e9854400eL, 0xbe65901f7b189932L, 0x4f97f3026299a369L);
    b.class_(false, false, false);
    b.origin("r:1564bb04-b8a2-4dfa-b7da-07b6754fa517(hedy.level1.structure)/5735319842049336169");
    b.version(2);
    b.property("value", 0x4f97f3026299a36aL).type(PrimitiveTypeId.STRING).origin("5735319842049336170").done();
    return b.create();
  }
}
